### ISSUE TITLE
Term for "Statistical Inference"

### ISSUE THREAD

**Issue by nicholsn** [ISA-tools/stato#12]
Another term we would like to see included is `Statistical Inference`. NCI has a definition for "Inference" that a little more general than what we are looking for (http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#C75591). Here is the definition:

```
"The process by which conclusions are derived from stated facts by the application of logical rules."
```

Do you already have a term for this concept or is this new?

**Comment by proccaserra** [comment]
@nicholsn we're working on it. we are currently importing a term from OBI 'drawing conclusion based on data' , we'll create subtype , I'll notify when done and provide the STATO id
thx

**Comment by proccaserra** [comment]
@nicholsn STATO_0000299: statistical inference

**Comment by nicholsn** [comment]
great, thank you!
