### ISSUE TITLE
Generality of "model parameter estimate" & "model parameter estimation"

### ISSUE THREAD

**Issue by nicholst** [ISA-tools/stato#18]
Following on discussions with @nicholsn & @cmaumet over at [ni-/ni-dm](https://github.com/ni-/ni-dm), we found some issues with model parameter estimat\* terms. 

The definition of `model parameter estimate` currently is linked to "regression analysis".  Of course model parameter estimation is a fundamental procedure in statistics and applies to any parametric model (including, e.g., multviariate, time series, survival, graphical models, etc).

Fortunately, there seems to be an elegant solution:  Just truncate the definition.  I.e. shorten it so that it reads
- a model parameter estimate is a data item which results from a model parameter estimation process.

Then, for "model parameter estimation", how about:
- model parameter estimation is a data transformation that finds parameter values most compatible with the data as judged by the model.

That is plenty agonistic, without talking about likelihood (as you'd then have to distinguish between LRT vs Method-of-Moment estimators, pseudo-likelihood/GEE, etc).  Heck, you could even drop "as judged by the model" if you want to be most flexible.

**Comment by proccaserra** [comment]
@nicholst  thanks for the review and suggesting fixes to the definitions.
If more terms are needed, please open an issue, providing use cases and definitions (textual and formal) or documentation. bw
