### ISSUE TITLE
Definition of "alternative hypothesis"

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#26]
Hi,

I was wondering if there is a word missing in the definition of "alternative hypothesis"  (copied from [bioportal](http://bioportal.bioontology.org/ontologies/STATO/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000208)): 
"alternative hypothesis is an **hyopthesis** defined in a statistical which is the opposite of the null hypothesis"

Should I read:
"alternative hypothesis is an **hypothesis** defined in a statistical **test** which is the opposite of the null hypothesis"
?

Thank you.

**Comment by agbeltran** [comment]
Yes, you are absolutely right. We will correct this soon. 
Thanks for the report.

**Comment by cmaumet** [comment]
Great! Thank you for the quick feedback.
