### ISSUE TITLE
Non-parametric symmetric distribution

### ISSUE THREAD

**Issue by agbeltran** [ISA-tools/stato#31]
Term added in https://github.com/ISA-tools/stato/pull/29
No ID has been assigned.
Needs more discussion with @cmaumet @nicholst about use cases.
@proccaserra proposes to add a new term `symmetric distribution` and obtain this one by post-coordination. I agree.

**Comment by cmaumet** [comment]
Thanks @agbeltran! 

Here is an example of use case:

```
niiri:error_model_id a prov:Entity , nidm:ErrorModel ;
    nidm:hasErrorDistribution nidm:NonParametricSymmetricDistribution ;
    nidm:errorVarianceHomogeneous "false"^^xsd:boolean ;
    nidm:varianceSpatialModel nidm:SpatiallyLocal ;
    nidm:hasErrorDependence nidm:IndependentError ;
```

(cf. also slides 27-28 in [this presentation](http://www.slideshare.net/cmaumet/supporting-imagebased-metaanalysis-with-nidm-standardized-reporting-of-neuroimaging-results).)

Please let us know if this helps and if you need further details.
