### ISSUE TITLE
Basic linear model estimation methods

### ISSUE THREAD

**Issue by nicholst** [ISA-tools/stato#32]
Following on discussions with @cmaumet, it seems notable that there are no definitions for the major flavours of estimation methods for linear models (aka multiple linear regression).  I'm referring to OLS, WLS, and GLS:
- **Ordinary Least Squares**.  Estimation method for a linear regression model when the errors are uncorrelated and equal in variance.  Is the Best Linear Unbiased Estimation (BLUE) method under these assumptions, Uniformly Minimum-Variance Unbiased Estimator (UMVUE) with addition of a Gaussian assumption.  http://en.wikipedia.org/wiki/Ordinary_least_squares .
- **Weighted Least Squares**.  Estimation method for a linear regression model with errors that independent but have heterogeneous variance.  Difficult to use use in practice, as weights must be set based on the variance which is usually unknown.   If true variance is known, it is the Best Linear Unbiased Estimation (BLUE) method under these assumptions, Uniformly Minimum-Variance Unbiased Estimator (UMVUE) with addition of a Gaussian assumption. http://en.wikipedia.org/wiki/Least_squares#Weighted_least_squares .  See also practical implementation as Iteratively Reweighted Least Squares.  http://en.wikipedia.org/wiki/Iteratively_reweighted_least_squares .
- **Generalised Least Squares**. Estimation method for a linear regression model with errors that are dependent and (possibly) have heterogeneous variance. Difficult to use use in practice, as covariance matrix of the errors must known to "whiten" data and model.   If true covariance is known, it is the Best Linear Unbiased Estimation (BLUE) method under these assumptions, Uniformly Minimum-Variance Unbiased Estimator (UMVUE) with addition of a Gaussian assumption. http://en.wikipedia.org/wiki/Generalized_least_squares .  See also practical implementation as Feasible Generalized Least Squares  http://en.wikipedia.org/wiki/Generalized_least_squares#Feasible_generalized_least_squares .

Since these reference yet 2 other methods, I might as well define those too...
- **Iteratively Reweighted Least Squares**. Practical implementation of Weighted Least Squares, where the heterogeneous variances of the errors are estimated from the residuals of the regression model, providing an estimate for the weights. Each successive estimate of the weights improves the estimation of the regression parameters, which in turn are used to compute residuals and update the weights. http://en.wikipedia.org/wiki/Iteratively_reweighted_least_squares .
- **Feasible Generalized Least Squares**.  Practical implementation Generalised Least Squares, where the covariance of the errors is estimated from the residuals of the regression model, providing the information needed to whiten the data and model. Each successive estimate of the whitening matrix improves the estimation of the regression parameters, which in turn are used to compute residuals and update the whitening matrix.  http://en.wikipedia.org/wiki/Generalized_least_squares#Feasible_generalized_least_squares .

What do you think @proccaserra?  GLS is important for NIDM as fMRI time series models use it routinely.

**Comment by cmaumet** [comment]
Just to complement @nicholst's request, here is an example of use (of OLS) within NIDM:

<pre>
niiri:model_pe_id a prov:Activity , nidm:ModelParametersEstimation ;
    rdfs:label "Model parameters estimation" ;
    <b>nidm:withEstimationMethod nidm:OrdinaryLeastSquares ;</b>
    prov:wasAssociatedWith niiri:software_id ;
    prov:used niiri:design_matrix_id .
</pre>
