### ISSUE TITLE
Identifier for stato:'ordinary least squares estimation' 

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#33]
Hi,

I have just sent a pull request at incf-nidash/nidm#252, to re-use the linear model estimation methods introduced in stato #32, thank you for those new terms and definitions!

I have noticed that the URI for stato:'ordinary least squares estimation' is using a text identifier while other estimation methods have alphanumeric ids (cf. screenshots). Could you let me know if this is intentional? 

| OLS | GLS |
| --- | --- |
| ![image](https://cloud.githubusercontent.com/assets/5374264/6398210/fc1718bc-bde1-11e4-93af-3a9f6f6a9be9.png) | ![image](https://cloud.githubusercontent.com/assets/5374264/6398193/de4422e4-bde1-11e4-8a41-819bb010a0e0.png) |

Thank you

**Comment by agbeltran** [comment]
Thanks Camille. Yes, I have seen that and will push some commits fixing this.

**Comment by agbeltran** [comment]
BTW, it is not intentional - I need to assign the ID that will be: http://purl.obolibrary.org/obo/STATO_0000370

**Comment by cmaumet** [comment]
@agbeltran: Thank you. I will update this identifier accordingly in incf-nidash/nidm#252.
