### ISSUE TITLE
"contrast weight estimate" re-labelled "contrast estimate"?

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#34]
Hi,

Following #23, the term "contrast weight estimate" was created in stato. I wonder if this term would be better labelled "contrast estimate" as it is not the weights themselves that are estimated but the contrast defined by them. @nicholst: would you agree with that?

How would you feel about this?

(We could then re-use this term in relation to `nidm:ContrastMap`).

**Comment by nicholst** [comment]
Yes, I concur with this. As previously discussed, there is much ambiguity with contrasts in general, but with "contrast estimate" there is no ambiguity, and it is clear that we're taking about c\hat{\beta}, ie the weighted sum of estimated parameters as specified by the "contrast weights". (And as the contrast weights c are always known and never estimated, there is no ambiguity there.

**Comment by agbeltran** [comment]
Hi @cmaumet & @nicholst,

I see what you mean about re-labelling, but am I right that the PR #37 creates a new term instead of re-labelling the existing 'contrast weight estimate' (STATO_0000324)?

Thanks

**Comment by cmaumet** [comment]
Hi @agbeltran! Yes, you are right, #37 creates a new term for "contrast estimate" rather than renaming "contrast weight estimate" as suggested here. I was not sure what you wanted to do with "contrast weight estimate" so I just thought I would rather create a separate term... (Also, I don't think a "contrast estimate" would be a child of "model parameter estimate" so this ended up being more than just re-labelling...).

If that's fine with you, I am happy to close this issue and discuss at #37 instead?

**Comment by cmaumet** [comment]
I am closing this issue as this has been discussed and updated in the merged pull request #37.
