### ISSUE TITLE
New term "residual mean squares"

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#35]
Looking in STATO, I could not find a term for "residual mean squares". I was therefore wondering if we could add such a term with the following definition: "residual sum of squares divided by the number of degrees of freedom" (from the ["Mean squared error" article in wikipedia](http://en.wikipedia.org/wiki/Mean_squared_error#Regression)). More details are also available in: [Understanding mean squares](http://support.minitab.com/en-us/minitab/17/topic-library/modeling-statistics/anova/anova-statistics/understanding-mean-squares/). (@nicholst)

(This term could then be re-used at nidm for the definition of `nidm:ResidualMeanSquaresMap`.)

Please let me know if I missed the corresponding term in STATO or if you need more information about this proposed new term. Thank you!

**Comment by nicholst** [comment]
This is a good one to discuss as it is important to get its relationship correct w.r.t. to other elements of the STATO ontology.

“Residual Mean Square” is a fundamental quantity in any linear model (STATO_0000108).  Under standard assumptions of the linear model (additive errors that are independent and have common variance) “Residual Mean Square”, the sum of squares of “Residuals” (IAO_0000234)  divided by the error "degrees of freedom" (STATO_0000069) is the “unbiased” (?) "estimate” (STATO_0000144) of the error “variance” (STATO_0000113).  

Is this 

I see that Residuals are defined in STATO, but in a way that is quite general.

Should you ever want to refine that there are, of course, there are a bountiful collection of residuals to enumerate: ordinary “Residuals” which are data minus fit, 
“Standardized Residuals” that are residuals divided by an estimate of their standard deviation; linear model textbooks will distinguish between “Internally Standardized Residuals” and “Externally Standardized Residuals”, where the form are usual “Standardised Residuals” and the latter standardise residual i using an estimated standard deviation computed from a model fit without observation i.  "Externally Standardized Residuals” are sometimes also called “Studentized Residuals”, as they exactly follow a Students T distribution with DF equal to the model DF minus 1.

In non-linear models, specifically for binary or count data, ordinary residuals aren’t very useful.  Here, “Pearson’s Residuals” are the standard tool, defined as data minus fit divided by the square root of the fit. (Text books usually write it (O-E)/sqrt(E), with O for Observed, E for expected).  Also used here are “Deviance Residuals”, these are per-observation contributions to the “Deviance” with a sign determined by the ordinary residuals.  “Deviance” is an important concept for discrete data modelling, and is -2 times the log-likelihood ratio of the fitted model compared to a saturated model.

There are yet more flavours of residuals (e.g. randomised quantile residuals), but the above are the main ones you see in the wild (and, to be honest, I guess the terms  “Internally Standardized Residuals” and “Externally Standardized Residuals” you don’t hear much outside of a class on linear models).

On 27 Feb 2015, at 11:09, Camille Maumet notifications@github.com wrote:

> Looking in STATO, I could not find a term for "residual mean squares". I was therefore wondering if we could add such a term with the following definition: "residual sum of squares divided by the number of degrees of freedom" (from the "Mean squared error" article in wikipedia). More details are also available in: Understanding mean squares. (@nicholst)
> 
> (This term could then be re-used at nidm for the definition of nidm:ResidualMeanSquaresMap.)
> 
> Please let me know if I missed the corresponding term in STATO or if you need more information about this proposed new term. Thank you!
> 
> —
> Reply to this email directly or view it on GitHub.

---

Thomas Nichols, PhD
Professor, Head of Neuroimaging Statistics
Department of Statistics & Warwick Manufacturing Group
University of Warwick, Coventry  CV4 7AL, United Kingdom

Web: http://warwick.ac.uk/tenichols
Email: t.e.nichols@warwick.ac.uk
Tel, Stats: +44 24761 51086, WMG: +44 24761 50752
Fx,  +44 24 7652 4532

**Comment by agbeltran** [comment]
Thanks, @cmaumet and @nicholst. 

You are right, as I don't think we have the term 'residual mean square'.

We could add this term with the following basic information:

```
label: residual mean square

alternative terms: error mean square, MSE

textual defintion: a residual mean square is a data item which is the output of the residual sum of squares divided by the number of degrees of freedom

definition source: 
http://en.wikipedia.org/wiki/Mean_squared_error#Regression
http://support.minitab.com/en-us/minitab/17/topic-library/modeling-statistics/anova/anova-statistics/understanding-mean-squares/
https://github.com/ISA-tools/stato/issues/35

parent term: data item
logical defintions: 
    'is about' some 'residual' (http://purl.obolibrary.org/obo/STATO_0000234)

(we can expand here to include the relationships with other terms in STATO, as described by @nicholst, but I need to explore what are the proper properties for this)

example of usage: 
used as an unbiased estimator of teh variance for a regression model
```

From the points above by @nicholst, we will also need to consider adding other terms such as:
- unbiased estimator
- residual sum of squares (RSS) with synonyms error sum of squares (SSE)
- subclasses of residual

**Comment by proccaserra** [comment]
@agbeltran this is great. Just one minor comment about the definition:
textual definition: a residual mean square is a data item which is obtained by dividing the sum of squared residuals (SSR)  by the number of degrees of freedom 
(as i found it easier to read and easier to then write the axioms using stato classes for 'residual' and 'number of degree of freedom)

**Comment by agbeltran** [comment]
Sure. BTW, we could also add the SSR term if needed, as I don't think we have it yet.

**Comment by cmaumet** [comment]
@agbeltran, @proccaserra: thanks a lot for your quick reply! The proposed term information seem good to me too.

**Comment by nicholst** [comment]
+1
