### ISSUE TITLE
Defined preferred mathematical notation in STATO

### ISSUE THREAD

**Issue by cmaumet** [ISA-tools/stato#41]
I was wondering if we could add a new attribute in STATO to specify an appropriate mathematical notation (when applicable). For instance:
- a 'p-value' is typically denoted by a 'p', 
- a 'q-value'  by a 'q', 
- an F-statistic by a 'F'
- a T-Statistic by a 'T' ...

My use-case is a [script](https://github.com/cmaumet/nidmresults_paper/blob/b4d9165aeba4b5a372b835a03054f1dd0531970d/query_results_report.py#L54) that we use against NIDM-Results examples to create a small paragraph describing the experiment.

If you are okay with this idea, I can write the corresponding pull request. 

Thank you in advance for your feedback!

**Comment by agbeltran** [comment]
Thanks @cmaumet for the suggestion, we've added a new annotation property 'preferred mathematical notation' (http://purl.obolibrary.org/obo/STATO_0000404) and annotated some of terms.

**Comment by cmaumet** [comment]
Thank you! That's great! I will update our [script](https://github.com/cmaumet/nidmresults_paper/blob/b4d9165aeba4b5a372b835a03054f1dd0531970d/query_results_report.py#L54) to use these notations directly.
