### ISSUE TITLE
use of invalid property IDs [PRS-rename: update to latest OBI release 2016-10-11]

### ISSUE THREAD

**Issue by stuckyb** [ISA-tools/stato#45]
I noticed that STATO is still using BFO IDs for a bunch of properties that have been moved to RO.  E.g., "concretizes", "has participant", "inheres in", etc. etc.  These properties have all been removed from BFO, so if STATO would update its usage of these terms to use the RO IDs, it would make STATO much easier to integrate with other reference ontologies.

**Comment by proccaserra** [comment]
@stuckyb this is down to our current import of OBI. upgrading to the latest release should fix the issue.
thanks for reporting. Can you tell us which other resources you are integrating STATO with?
thx

**Comment by stuckyb** [comment]
Sure -- I'm working with a group that is developing on ontology for plant phenology data, and we are considering importing some STATO terms.  We ran into problems because other ontologies from which we import terms use the RO versions of terms, not the older BFO versions used by STATO.

**Comment by proccaserra** [comment]
Awesome, I guess the project is http://icbo.cgrb.oregonstate.edu/node/326 ?
we should have a call and talk as we are involved in a project in Europe where your resource could be very useful .

**Comment by stuckyb** [comment]
Yes, that is the project!  And yes, would be great to talk some time.
