### ISSUE TITLE
How to link a probability distribution to its parameters?

### ISSUE THREAD

**Issue by cfrancois7** [ISA-tools/stato#47]
I'm integrating STATO ontology in mine to describe the probability distribution. However, it seems to not exist the class for the parameters of a probability distribution, e.g. the gamma distibution and its shape and scale parameters.

How do you recommend to link a distribution to its parameters ?

**Comment by proccaserra** [comment]
@cfrancois7 we can add 'probability distribution shape parameter' & 'probability distribution scale parameter' entities to STATO and use either 'denotes' relation or create a specific one to link the 2 entities.
We rely on such mechanism to relate skewness, kurtosis, variance to distributions already.

If you provide us with the name of your ontology or project, we could also link to it from the documentation. cheers.

**Comment by nicholst** [comment]
Are "mean" and "variance" terms already connected as such?

**Comment by proccaserra** [comment]
@nicholst , yes, { 'expected value', variance, kurtosis, skewness , 'standard deviation'}

**Comment by cfrancois7** [comment]
Thank you for the answer.

Soon, I'll share the part of my ontology about what parameters I need. My purpose is to store the probability distribution and its parameters in the ontology with the python code (such as your R code). Also, it seems the log-normal probability distribution is missing. I'm working in the Industry Ecology studies and the log-normal is used very often due to the advantages to propagate the uncertainty by a _Taylor discrete_ transformation.

**Comment by cfrancois7** [comment]
Thanks you for the update.

You defined `probability distribution scale parameter` as a `data item`. Could not be better defined as a `measure of variation` ?

The scale parameter represents the "spreadedness" such as the "variance" or the "standard deviation". For instance the standard deviation is the scale parameter of a normal distribution.
