### ISSUE TITLE
location parameter for logistic distribution (and other location-scale family)

### ISSUE THREAD

**Issue by cfrancois7** [ISA-tools/stato#50]
I would like to know how to deal with the location parameter for the logistic distributions, log-normal distribution or other[ location-scale distribution family](https://en.wikipedia.org/wiki/Location-scale_family).

I didn't find an appropriated class in STATO. Thanks in advance.

**Comment by proccaserra** [comment]
@cfrancois7 thanks for request. We need to do some more reading but, as for scale parameter, it would initially be cast as a subtype of 'data item' as it is used to define a parametric distribution, unless we create a new class 'measure of spatial location' (to indicate it is only meaningful in the context of graphical representation but don't take the suggested class label to the letter, it would a placeholder until we come up with a more suitable label.  We would need to create a 'location parameter estimator' class. We may also want/need to capture the fact that for normal distribution, the location parameter is the mean, not to mention logistic distribution. hence, more reading :), bear with us.

**Comment by cfrancois7** [comment]
Thank you for your reply.

In my point of view the mean is not the location parameter in a normal distribution. It is just when the shift is null regarding the "standard/reference" normal distribution.

[formula of a normal distribution](https://wikimedia.org/api/rest_v1/media/math/render/svg/6404a4c69c536278a5933085f0d5f4a9ca9f2b2a)

In the mathematical form the mean is not the location parameter, but sometimes the location parameter is equal to zero and we get a standard normal distribution. It is only a particular normal distribution, kind of, could be `subclass-of` normal distribution.

After it is difficult to define the location parameter because it depends of the mathematical formula of the distribution. But by essence it is a shift from where starts the distribution for a non-symmetrical distribution and where is the mean for a symmetrical distribution.
