### ISSUE TITLE
Contact page on frog.oerc is down/moved

### ISSUE THREAD

**Issue by sneumann** [ISA-tools/stato#52]
Hi, http://stato-ontology.org/ is linking to:
http://frog.oerc.ox.ac.uk:8080/stato-app/contact.jsp
which is currently down. Yours, Steffen

**Comment by proccaserra** [comment]
Hi @sneumann , thx for reporting but i can not reproduce here (tested on 4G connection). may be a blip. please let us know if still unavailable from your end. best

**Comment by sneumann** [comment]
Hi, indeed could've been a glitch anywhere between my desk and the other side of the channel.
