### ISSUE TITLE
Coordination with AGRO

### ISSUE THREAD

**Issue by pbuttigieg** [ISA-tools/stato#54]
Hi STATO team!

Over at the [Agronomy Ontology](https://github.com/AgriculturalSemantics/agro/), we're developing an ontology-driven fieldbook for the [CGIAR](http://www.cgiar.org/). 

We'll be using classes like `split-plot design`, `treatment`, `factor` for agronomic trials. We would like to import most/all such material from STATO. Would you be available/actively developing in the next few months so we can push requests your way as they arise?

CC: @marieALaporte @brianjlowe @elizabetharnaud @mdevare

**Comment by proccaserra** [comment]
Hi @pbuttigieg ! nice to hear from you. The development is on, we are about to make a new release, so this is very timely. Please do send your term requests. We'll talk soon. ATB.

**Comment by agbeltran** [comment]
@pbuttigieg @marieALaporte @brianjlowe @elizabetharnaud @mdevare - just following up from your comment, do let us know if you have any term requests. Thanks!

**Comment by pbuttigieg** [comment]
Thanks for the reminder, I'll put some together tomorrow.

**Comment by pbuttigieg** [comment]
@marieALaporte @brianjlowe @elizabetharnaud @mdevare

I've created a few requests (cross-linked above), but your input for treatments and designs would certainly be more on-point for AGRO's use cases.
