### ISSUE TITLE
Statistical inference (STATO_0000299) definition too narrow

### ISSUE THREAD

**Issue by nicholst** [ISA-tools/stato#55]
Statistical inference is generally regarded as the process of drawing conclusions from data using some form of model.  It is _not_ confined to hypothesis tests, as suggested in the STATO definition:

> statistical inference is a process of drawing conclusions following data analysis using statistical methods (statistical tests) and evaluating whether to reject or accept null hypothesis.

As reflected in this statisticians general accepted definition and in [Wikipedia](https://en.wikipedia.org/wiki/Statistical_inference) "Statistical inference is the process of deducing properties of an underlying probability distribution by analysis of data" and includes a point estimate, an interval estimate (e.g. a confidence interval) or rejection of a hypothesis.

I can propose a simple modification consisting of a truncation of the STATO definition:

> statistical inference is a process of drawing conclusions following data analysis using statistical methods.

(With @cmaumet)

**Comment by agbeltran** [comment]
Thanks @nicholst  @cmaumet - I would go for the definition in Wikipedia, which comes from the Oxford Dictionary of Statistics according to their citation. So, we can include "Statistical inference is the process of deducing properties of an underlying probability distribution by analysis of data." as definition, and indicate the definition source.

**Comment by agbeltran** [comment]
I've implemented the change including the definition from Wikipedia/Oxford Dictionary of Statistics. If you agree, we can close this issue. Thanks!

**Comment by nicholst** [comment]
Thanks!

**Comment by agbeltran** [comment]
thanks for raising the issue! closing...
