### ISSUE TITLE
Coordinate 'population' semantics with PCO

### ISSUE THREAD

**Issue by pbuttigieg** [ISA-tools/stato#56]
@ramonawalls @proccaserra 

STATO imports an OBI term [`population`](http://purl.obolibrary.org/obo/OBI_0000181). The semantics get a little wonky here as a statistical population differs from an ecological population. A class for `statistical population` should be made, either in STATO or PCO (I'm guessing the former is better).

Something like:
```
'statistical population' =def. 'A collection of entities which share one or more properties and which is the target of a statistical analysis. 
```

The `statistical analysis` process would thus have an `objective specification` that identifies and delineates the population. 

It's important to note that statistical populations may also consist of non-material things (e.g. simulation outputs) or processes. Thus, STATO should have quite a broad class here.

'Object' can be handled by BFO. 

[PCO](https://github.com/PopulationAndCommunityOntology/pco) has the semantics to handle a broad range of populations and I recommend that STATO imports either PCO's [`collection of organisms`](http://purl.obolibrary.org/obo/PCO_0000000) for all kinds of biotic statistical populations or [`population of organisms`](http://purl.obolibrary.org/obo/PCO_0000001) to deal with single species collections. 

There's a good chance to build some useful axiomatisations here.

**Comment by agbeltran** [comment]
I agree with you that we should have a 'statistical population' term, which should be more generic than just material entities. 

But the limitation in the representation arises from relying on BFO, which splits the world into continuants and occurrents/processes, and within continuants, splitting between independent continuants (e.g. material entities) and generically dependent continuants (e.g. information content entities), etc. 

We did define 'study group population' (equivalent to 'statistical sample') but it has the same problem of being a 'material entity' at the moment.
