### ISSUE TITLE
NTR: plot, subplot and restricted randomized designs

### ISSUE THREAD

**Issue by pbuttigieg** [ISA-tools/stato#58]
xref to #54 
This request has two parts

### Restricted randomized designs
Designs based on [restricted randomisation](https://en.wikipedia.org/wiki/Restricted_randomization) are particularly relevant for agricultural semantics, but are universally important. I couldn't find classes like 'split-plot design' or 'strip-plot design' under [`study design`](http://purl.obolibrary.org/obo/OBI_0500000). Could these be added?

### Plot and subplot
These are the sites where [split-plot designs](https://en.wikipedia.org/wiki/Restricted_randomization#Split-plot_designs) are concretised and realised. As these pertain to physical sites, ENVO could import and axiomatise with a class like split-plot design from STATO, to create a term that refers to the site where the design is C&Red. Shall we try this? AGRO can then ingest this neatly.

**Comment by pbuttigieg** [comment]
see also: [Points of Significance: Split plot design ](http://www.nature.com/nmeth/journal/v12/n3/full/nmeth.3293.html)

**Comment by proccaserra** [comment]
@pbuttigieg these are already in my branch, we are due a new release, they will appear then.
it will include split-plot design, split-split plot design as well as 'restricted randomization', with axiomatic definition
