### ISSUE TITLE
Proposed revision to 'weighted arithmetic mean'

### ISSUE THREAD

**Issue by dillerm** [ISA-tools/stato#59]
I'm interested in using this class in our ontology--Apollo-SV--but noticed that it does not reflect the correct parent class and could be more descriptive.

The current definition for this class is as follows:

> The weighted arithmetic mean is a kind of mean similar to an ordinary arithmetic mean (the most common type of average), except that instead of each of the data points contributing equally to the final average, some data points contribute more than others. 
> 
> The weighted arithmetic mean is often used if one wants to combine average values from samples of the same population with different sample sizes.

As such, I would like to offer the following proposed revision to see if you think it might be worth adopting:

> The weighted arithmetic mean is a measurement datum that is the sum of the products of each observed value and their respective non-negative weights, divided by the sum of the weights, such that the contribution of each observed value to the mean may defer according to its respective weight. It is defined by the formula: A = sum(vi*wi)/sum(wi), where 'i' ranges from 1 to n, 'vi' is the value of each observation, and 'wi' is the value of the respective weight for each observed value.

Not sure if you would want to include that last part in the definition or as a comment so as to make the definition less clunky.

**Comment by proccaserra** [comment]
@dillerm +1 we will update the definition with your contribution, which is more precise. it will appear a new release, which is in the making.

**Comment by dillerm** [comment]
Thank you. Glad I could help!

**Comment by agbeltran** [comment]
Thanks @dillerm! The current definition certainly needs improvement.

We currently refer to [Wikipedia's definition](https://en.wikipedia.org/wiki/Weighted_arithmetic_mean), we could also refer to the [Oxford Dictionary of Statistical Terms](https://books.google.co.uk/books?id=_OnjBgpuhWcC&pg=PA429&lpg=PA429&dq=%22Weighted+arithmetic+mean%22+oxford+dictionary+of+statistics&source=bl&ots=VtInXVrPAG&sig=iuRhwnAnTdgR3yL4e6MNcGYTgxU&hl=en&sa=X&ved=0ahUKEwittaXL2t7VAhUSalAKHT91BfoQ6AEIKDAA#v=onepage&q=%22Weighted%20arithmetic%20mean%22%20oxford%20dictionary%20of%20statistics&f=false ).

We also need to add the following annotations:
-  synonym/'alternative term': ```weighted average```
- 'R command': [weighted.mean(x, w, ...)](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/weighted.mean.html)
- 'Python command': [numpy.average](https://docs.scipy.org/doc/numpy/reference/generated/numpy.average.html)
