### ISSUE TITLE
hypergeometric, binomial, fisher; one-side vs two-sided

### ISSUE THREAD

**Issue by cmungall** [ISA-tools/stato#6]
We may need new classes to support the different types of test offered by GO enrichment tools. Examples of those offered include:
- Fisher (present in STATO)
- Hypergeometric
- Binomial
- Chi-squared

However, some may be inappropriate or equivalent or underspecified; e.g. hypergeometric and fishers.

Ref: http://bioinformatics.oxfordjournals.org/content/23/4/401.full.pdf

I can provide more specific details later, just want to file this as a placeholder for now

**Comment by proccaserra** [comment]
Hi Chris,
We leave the ticket open as we are still digging into the representation of other aspects discussed in the paper in keeping with one or two sided tests.

**Comment by proccaserra** [comment]
@cmungall

Following up on your term requests, please find below the tests and corresponding ids.

Pearson's Chi square test: STATO_0000081
hypergeometric test: STATO_0000285
one tailed test: STATO_0000286
two tailed test: STATO_0000287
exact binomial test: STATO_0000298

We have not precomposed the various possible one.two tailed tests for now
 but we don't rule it out.
We have been testing formal representation considering the hypothesis being tested by either of the tests.

If you are fine with having to qualify some of your tests with 2 STATO terms , we can consider this a closed issue. Feel free to reopen it if you'd rather have precomposed classes.

Best

**Comment by cmungall** [comment]
this is great, thanks
