### ISSUE TITLE
Release Turtle or RDF/XML Version

### ISSUE THREAD

**Issue by jpmccu** [ISA-tools/stato#65]
OWL/XML isn't as widely supported as RDF/XML. It would be nice if there were a stato.rdf or stato.ttl released alongside stato.owl for easier integration with other systems. The main extant OWL/XML parser is OWLAPI, which means support for OWL/XML is restricted mostly to Java systems.

**Comment by proccaserra** [comment]
@jimmccusker we'll be looking into this. initial test using protege 5.1 shows some problems dealing with imports when round tripping.
