### ISSUE TITLE
go:molecular function inconsistent with source ontology

### ISSUE THREAD

**Issue by jpmccu** [ISA-tools/stato#66]
In STATO, it is listed as a bfo:function, but in GO itself, it is a bfo:process. These are disjoint at the occurrent/continuant level. This results in inconsistent reasoning when merging STATO with other OBO ontologies, including GO, HP, CMO, and UBERON.

**Comment by agbeltran** [comment]
In STATO, ```GO:molecular_function```comes from the OBI import. In OBI, ```GO:molecular function``` is indeed a subclass of ```BFO:function``` (see [GO:molecular function as part of OBI in OLS](https://www.ebi.ac.uk/ols/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003674)). 

Checking GO itself, it does not have a direct relationship with BFO (I checked the [OWL file](http://purl.obolibrary.org/obo/go.owl) and also [GO in OLS](https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003674)).

I do see that in HP, ```molecular_function``` is a subclass of ```process```(checking in [OLS](https://www.ebi.ac.uk/ols/ontologies/hp/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0003674)).

So, it seems that the inconsistent comes from how OBI and HP (and possibly the others you mentioned) deal with mapping GO to BFO, and we should follow up by raising the issue with those ontologies.

**Comment by proccaserra** [comment]
pointing those issues to the OBO foundry now, @jimmccusker thx for reporting @agbeltran thx for investigating further.

**Comment by agbeltran** [comment]
@jimmccusker I've pushed the new import module from OBI, whose latest release included the fix of this issue that you reported, than you! This is currently in STATO development version in this repository, and it will be included in the upcoming STATO release.
