### ISSUE TITLE
Add 'df calculation'

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#68]
Hi,
Currently in STATO there is a 'degree of freedom approximation' class (STATO_0000472) with more specific approximation methods as subclasses. Could you add a superclass 'degree of freedom calculation' for the cases where no specific procedure other then using a standard formula is needed? Or maybe, 'df approximation' could be renamed to 'df calculation' ?
Additionally, 'number of degree of freedom' (STATO_0000069) could be linked as an output from the procedure.

**Comment by hcwi** [comment]
Another df-related remark:
'df approximation' is currently linked to 'model fitting' (STATO_0000218) by 'has part', along with 'statistical hypothesis test' (OBI_0000673). To me it seems more directly part of the testing. 
How about adding/moving 'df calculation/approximation' to 'statistical hypothesis test'?

**Comment by proccaserra** [comment]
@hcwi can certainly do. the current representation came from a use case where the model fitting process called for more details to reported about how df were estimated but you are right I will add an axiom to reflect this point. tx

**Comment by hcwi** [comment]
Thanks for addressing my request! 
From what I see in the dev version, the remaining thing to consider at some point might be the relationship between 'df_calculation' and 'df_approximation'. Imo, the latter is a specification.
