### ISSUE TITLE
Parameterisation of covariance structures

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#70]
Hi,
specific covariance structures (subclasses of STATO_0000346) are characterised by a set of parameters that are estimated in the modelling process, e.g.
 - Identity covariance structure (#69) -> sigma
 - compound symmetry -> sigma, rho
 - autogressive -> sigma, rho

etc. The parameters are called 'variance parameters' or 'variance components' and are reported in the resutls of the analyses, such as linear mixed models. 
If you think it makes sense to take note of this linkage in STATO, then 'covariance structure' could be added something like:
'has part'(?) some 'variance parameter'(?) / 'variance component'
(I've found there is already a 'variance component estimate' in the dev version of STATO)

In general 'variance parameter/component' is a 'parameter', and in the sense of being an object estimated in the model, also a 'model parameter' (STATO_0000034).

**Comment by proccaserra** [comment]
@hcwi I am inclined to start with a conservative approach, ie simply adding an axiom 'has part' some 'model parameter' to those covariance structures listed.  One reason for this: the possible proliferation of sigmas, rhos, that would have to be defined. I am looking at https://bbolker.github.io/mixedmodels-misc/notes/corr_braindump.html  for example. Is that what you are trying to represent ? what are the queries you need to support? thx!

**Comment by hcwi** [comment]
Dear @proccaserra, 
I am ok with the conservative approach. The statements 'has_part some model_parameter' can apply to all covariance structures and can be used whenever some quantities describing the structures should be used. Exemplary queries I have in mind are related to comparison of estimated parameters of covariance structures in two models/datasets to verify which one fits better.

In fact didn't mean to specify all parameters by name (as different symbols can be used instead of the standard sigmas, rhos, lambdas etc. given in e.g. [Table 56.13](https://support.sas.com/documentation/cdl/en/statug/63347/HTML/default/viewer.htm#statug_mixed_sect020.htm#statug.mixed.randomstmt_type_un)) but to establish a pattern to declare them along with the covariance structure. 

The thing I would request to consider in the future, is specifying a subclass of 'model parameter' called 'variance parameter' that would indicate its role as a parameter of some covariance structure model.
