### ISSUE TITLE
Add 'num df' and 'den df'

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#71]
Hi,
I am missing from STATO the terms 'numerator degrees of freedom' and 'denominator degrees of freedom' to quickly distinguish between 'number of degrees of freedom' (STATO_0000069) for F-distribution and F-tests. Unless I have overlooked some other way to do this, it might be useful to add them.

**Comment by proccaserra** [comment]
hi @hcwi would you be able to provide more background information? are you asking to create subtypes of 'ndf' , one for the 'model' and the other for the 'error' (as discussed in https://math.stackexchange.com/questions/617735/multiple-regression-degrees-of-freedom-f-test) ?

**Comment by hcwi** [comment]
Despite closing the issue, let me summarise the discussion:

_F statistic_ is by definition a ratio of two mean squares, each with its _df_ number. The multiple regression is a special case of this, where "numerator" is the mean square for the whole model, and "denominator" is the means square for error. In general, F is for testing general hypotheses, e.g.  corresponding to a "term", not necessarily being the whole model. 

As to computation of both _df_ numbers - they can be exact or approximated by the approaches already included in STATO.

**Comment by hcwi** [comment]
And thanks for addressing the request!
