### ISSUE TITLE
Confidence level for confidence interval

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#72]
Suggestion to include 'confidence level' (STATO_0000561) as a part of 'confidence interval' (STATO_0000196)
It is implicitly done in the subclasses where specific level is included in the name and description only, e.g. '99% confidence interval'.

**Comment by hcwi** [comment]
Another remark to discuss:
Confidence interval is a result of interval estimation of a parameter, as opposed to the point estimation, which produces a single value 'estimate' and its error. Therefore, the statement in STATO:
`'confidence interval' 'is about' some 'effect size estimate'` (or any other estimate)
is not formally correct. Both the 'estimate' and 'confidence interval' are estimates of some parameter (model parameter, effect, etc.)

**Comment by proccaserra** [comment]
@hcwi confidence interval amended to link to confidence level. closing the issue but will address the issue about point estimation and interval estimation in subsequent commits
