### ISSUE TITLE
Consider adding a Function class

### ISSUE THREAD

**Issue by hcwi** [ISA-tools/stato#76]
Hi,
another request to discuss for STATO: adding a function (in mathematical sense).
There is already a _function_ class and properties _function of_ and _has function_ but only in the sense of 'role'.

In our data we would like to annotate parametric functions, that is functions of model parameters. For that a class represeting a function in a mathematical sense and some property (_function of_?) for linking its arguments are needed. Can you consider adding those or extending some existing definitions, or suggest us another way to go?

**Comment by proccaserra** [comment]
@hcwi it is possible to create a class 'mathematical function' as a type of 'information content entity'. This is will completely distinct from BFO:function. but we may need more discussion in case you are referring also to some programmatic function such as this one https://stat.ethz.ch/R-manual/R-devel/library/nlme/html/lme.html, where you would also want to list and represent all the arguments of such function. These type of functions would be implementation/language specific and possibly distinct from a true 'mathematical function' (they may coincide or they may not). I think we'd need more information and examples of queries. for example, going back to the lme R example: do you want to runquery such as: "if function=lme, retrieve value for argument 'method'"? I presume identifying the programming language may be needed if this is the use case at hand. best

**Comment by hcwi** [comment]
Dear @proccaserra,
For our use cases I meant a mathematical function, not a programmatic one. We would like to classify an object as a function, and say that it is derived from another object. Describing how exactly it is derived might be too specific and complex for an ontology, but a simple property "has_formula" might be useful to include.

I am thinking of modelling something like this:
```
<pf> rdfs:label "parameteric function" .
<pf> rdf:type STATO:function .
<pf> STATO:is_function_of <param1>, <param2>.
<pf> STATO:has_formula "param1+param2".
<param1> rdf:type STATO:model_parameter.
<param2> rdf:type STATO:model_parameter.
```
