### ISSUE TITLE
Allele Frequency

### ISSUE THREAD

**Issue by allysonlister** [ISA-tools/stato#80]
Good afternoon all! I have a question about http://purl.obolibrary.org/obo/STATO_0000254 please. Currently, the "STATO alternative term" property is used for this class, but its value is an empty string. I had thought that a previous version of this ontology had "gene frequency" as an alternative term. Could it be that "gene frequency" has accidentally been removed, or is there some other reason for the empty alternative term field?

Thanks very much! :) Allyson

**Comment by proccaserra** [comment]
hi @allysonlister , I went back and checked all the releases of STATO, the 'STATO alternative term' has always been empty. That's an oversight on my side when creating the class as I used a fix set of properties for all classes (more or less consistently) until switching to robot tool for handling the releases. 
Now, if you need the synonym, I'll add it. It seems the wikipedia definition for 'allele frequency' includes 'gene frequency' as alternative label.
https://en.wikipedia.org/wiki/Allele_frequency
also in:
https://www.sciencedirect.com/topics/medicine-and-dentistry/gene-frequency

**Comment by allysonlister** [comment]
It must have been some kind oddity of my brain that thought you had it in a previous release - my apologies @proccaserra ! It would be nice to have the synonym in the next release, if it isn't too much trouble.

Thanks! :) Allyson
