### ISSUE TITLE
Definition of mortality

### ISSUE THREAD

**Issue by mbrochhausen** [ISA-tools/stato#87]
Hi,

we are looking at mortality after trauma surgery. While we do, in general, greatly appreciate the STATO representation of mortality, there is one aspect that makes us concerned about reusing the class: The definition specifically stats that mortality is "a ratio formed by the number of deaths due to a disease divided by the total population size." We are looking at the death due to or occurring after an intervention made necessary by trauma. That does not sound to me like the number of deaths due to a disease (hinges on how you define disease).
We do this work as part of an NIH-funded project (just to give you some context).

**Comment by proccaserra** [comment]
@mbrochhausen, if still needed, I will alter the definition to replace 'disease' with 'event or procedure or disease'

**Comment by mbrochhausen** [comment]
@proccaserra, many thanks! We decided to go with the EFO mortality term. However, I think it would still be prudent to change the definition, but that is totally up to the STATO community. Thanks again!
