### ISSUE TITLE
Term for "Design Matrix"

### ISSUE THREAD

**Issue by nicholsn** [ISA-tools/stato#9]
Does stato or another ontology have a term for a design matrix (http://en.wikipedia.org/wiki/Design_matrix)?

If not, it would be great if this term could be included in stato. Thanks!

**Comment by proccaserra** [comment]
Hi Nolan,
stato does not have yet a term for design matrix but we could add it fairly quickly and get back to you.
We'll notify you as soon as we get the term in. Also, we could discuss use cases to refine the formal representation in keeping with models and variables.
Best
Philippe

**Comment by nicholsn** [comment]
Thanks, @proccaserra. I'm working on a data model/vocabulary for neuroimaging called [NI-DM](https://github.com/ni-/ni-dm), and will have more stats terms we'd like to define or refer to. Just remembered, another one is "Contrast" as in: http://en.wikipedia.org/wiki/Contrast_(statistics)... 

What's the best way to request terms? Is this an appropriate use of github issues?

**Comment by proccaserra** [comment]
@nicholsn No pb. wrt to term request, yes  please log those as github issues (thx for already including pointers to definitions). creating formal definitions can at times require more time.

**Comment by proccaserra** [comment]
Hi @nicholsn ,
we have now added the following terms:
design matrix: STATO_0000289
contrast: STATO_0000290

We have provided textual and formal definitions, and links to R commands.
We don't close the issue yet as an additional round to review has to take place.

It would also be interesting for us to document the intended usage of both terms in your project.
would you need 'contrast matrix' too?

Best
P

**Comment by nicholsn** [comment]
Awesome, it it great that these could be added so quickly. Is there a way to comment on the definitions? Do you use Pull Requests when making changes where you can comment on the line of a changed file?

**Comment by proccaserra** [comment]
Thx. You could add 'comment' annotation properties but, if you are fine with it, sending feedback via the github issue thread could be just as convenient. BW
