### ISSUE TITLE
Unsatisfiable classes in STATO

### ISSUE THREAD

**Issue by henrietteharmse** [ISA-tools/stato#90]
I stumbled across the following unsatisfiable classes in STATO in encountering them in the MS ontology:
![image](https://github.com/ISA-tools/stato/assets/32327979/35ff933b-fc1c-4088-8460-787dc3b9164f)

Here is the explanation for STATO_0000046 being unsatisfiable:
![image](https://github.com/ISA-tools/stato/assets/32327979/f9157f86-ef6b-4e56-b882-053ac2c3bf41)

What had me perplexed is that when reasoning on STATO, these unsatisfiable classes do not show up, when in fact they should.

The reason why these unsatisfiable classes are not showing up in STATO is that STATO are missing some axioms that are not imported from BFO and RO:

BFO:  `BFO_0000002 DisjointWith BFO_0000003`
RO: `BFO_0000051 o RO_0000057 SubPropertyOf: RO_0000057`

Adding these axioms to STATO and running the reasoner gives the exact same unsatisfiable classes encountered in MS:
![image](https://github.com/ISA-tools/stato/assets/32327979/290ac826-d8bc-4ded-aaf2-8d4d01a1fce2)

**Comment by proccaserra** [comment]
Hi @henrietteharmse , 

Thank you for reporting the issue and for providing a solution.
I need to dig into why these axioms aren't pulled.

**Comment by proccaserra** [comment]
- [x] making `continuant` disjoint from `occurrent`
- [x] adding SuperProperty of (Chain) `'has part' o 'has participant'`on `has participant` relation
- [x] fixing axioms on 2 plots (Q-Q plot, Lineweaver-Burk plot) and 8 study designs
