### ISSUE TITLE
F1 score  term addition to the STATO ontology 

### ISSUE THREAD

**Issue by Zainab-ik** [ISA-tools/stato#93]
Hi, 
I believe the F1 Score has a very statistical significance and should be classified with the likes of accuracy, precision especially when dealing with machine learning. 

The F1 score is the harmonic mean of the precision and recall. The two metrics contribute equally to the score, ensuring that the F1 metric correctly indicates the reliability of a model

Also, it's important to stick to a standard when annotating and I believe this standards makes using a model FAIR. 
I kindly request the term F1 score be added to the STATO ontology. 
Thanks. 

@proccaserra

**Comment by proccaserra** [comment]
@Zainab-ik absolutely. thank you for the request. It will be available in the coming release.

**Comment by Zainab-ik** [comment]
> @Zainab-ik absolutely. thank you for the request. It will be available in the coming release.

Oh, thank you. 
How soon is the release if i may ask or like a timeline @proccaserra ?

**Comment by proccaserra** [comment]
http://purl.obolibrary.org/obo/STATO_0000628

to appear in release 1.5
